### ISSUE TITLE
review

### ISSUE THREAD

**Issue by col3name** [Hariz0n/shri-react-hw-2023#1]
Критерии оценивания:

1. Реализована страница списка фильмов  0.5

  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется) 
   - [x] Работает переход по клику на фильм(либо на всю карточку, либо на название или постер)

   - [] Реализованы все ограничения и шаблоны ввода для фильтров(там где указаны)  (не обновляется url)

   - [] Реализованы ограничения на кол-во билетов

2. Фильтры 1

    - [x] Фильтрация работает - значения в списке фильтруются

3. Страница фильма  0.8

   - [] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется) отличается font-size, font-weight, padding 0.3

   - [x] Реализованы ограничения на кол-во билетов

4. Страница заказа  1

  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)
  - [x] Финальное кол-во билетов считается корректно
   - [x] Модально окно работает как описано

5. Страница о нас 1

 - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)

  - [x] Static (страница генериться на билде, а не на реквесте)

6. Страница вопросы/ответы 1

   - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)

   - [x] Static (страница генериться на билде, а не на реквесте)

7. Шапка 1

   - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)

   - [x] Позиционируется липко(стики)

8. Футер  1

  - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)

9. Модалка 1

   - [x] Верстка соответствует макетам(допускаются минимальные отхождения, адаптив не требуется)

   - [x] Используется портал

10. Стор  0.66

   - [x] Данные корректно разбиты на модули(пример - кинотеатры, фильмы, отзывы, авторы отзывов, корзина)

   - [] Селекторы написаны оптимально(нет кучи дублирования)

   - [x]   Данные грузятся только по необходимости(отзывы не надо грузить на странице списка фильмов и тд), если уже загружены, то повторно не загружаются.

11. Оптимизация  0.6

   - [] При изменении кол-ва билетов не перерендеривается вся карточка фильма(в списке фильмов, на странице фильма, в заказе), а только часть с количеством

   - [x]   2. Для картинок используется Image некста. Постеры(про список фильма), которые вне вьюпорта грузятся лениво

   - [x]  3. На полях фильтрации с свободным вводом есть debounce(фильтрация происходит только после окончания ввода)

**Comment by col3name** [comment]
0.5+1+0.8+1+1+1+1+1+1+0.66+0.6=9.69 ~ 10

**Comment by Hariz0n** [comment]
Спасибо за ревью. Правда я немного не согласен с некоторыми критериями

**1.4. Реализованы ограничения на кол-во билетов**
Ограничение на количество билетов было реализовано и на странице со списком фильмом, и на странице одного фильма. (В критерии 3.2 это засчитано). Ограничение в 30 билетов подразумевалось под каждый фильм
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/31e77d44-2417-4633-9c09-66430d24429e)
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/1ffae5fc-10d1-444e-a5f5-f807a3db326b)

**11.1. При изменении кол-ва билетов не перерендеривается вся карточка фильма**
Аналогично, вся карточка фильма при изменении количества не перерендеривается, а только часть с кнопками и самим счетчиком. У меня эта фича вынесена в отдельный компонент (EditCart.tsx)
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/a7d85409-872b-4b8f-85e5-cbf2911fdca2)

**11.3. На полях фильтрации с свободным вводом есть debounce**
В этом приложение поле с свободным полем одна - фильтр названия. И на нем как раз реализован дебаунс в 500 миллисекунд (компонент FilterPlainText.tsx)
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/67c86ff7-8e81-403e-88cb-3558b7ad6688)

Также хотел бы по подробнее узнать в чем проблема с селекторами и ограничениями и шаблонами фильтром.

**Comment by col3name** [comment]
1.4 когда кол-во билетов 1 и уменьшаем их кол-во должна показываться модалка с подтверждением удаления.
 Нижняя граница не обработана
 
 с 11 согласен

**Comment by Hariz0n** [comment]
> 1.4 когда кол-во билетов 1 и уменьшаем их кол-во должна показываться модалка с подтверждением удаления. Нижняя граница не обработана

Во все трех случаях (страница со списком, страница корзины и страница фильма) при попытке удалить последний билет выпадает модалка
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/3901cd29-ece5-4bb1-9cd4-1d2fab34cd0c)
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/16fd3d4c-67dd-44b9-8e2e-c53c1ddef99b)
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/37c67ca5-53ac-4015-b3b6-9d380c643ccd)

Также что по по поводу 11.1 и 1.3

**Comment by col3name** [comment]
поставил 10 баллов
1.4 нет модалки на странице списка фильмов
11.1 не обновил галочку

+ проект не собирается


./src/entities/Portal/ui/ReactPortal.tsx:10:22
Type error: Argument of type 'React.ReactNode' is not assignable to parameter of type 'import("/Users/mikha/IdeaProjects/yandex/shri/summer/react/hw-react/Hariz0n/frontend/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
  Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
    Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.

   8 | 
   9 | const ReactPortal = ({ children }: IProps) => {
> 10 |  return createPortal(children, document.body);
     |                      ^
  11 | };
  12 | 
  13 | export default ReactPortal;
error Command failed with exit code 1.

**Comment by Hariz0n** [comment]
Странно что проект не сбилдился. Сейчас попробовал с нуля его сбилдить и все вышло
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/0368faab-09d3-495c-ac8c-8d493a085796)

И все таки модалка на странице фильмов есть, как на других страницах. Сейчас проверил еще раз. 
![image](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/4c773025-df4c-4634-aa8a-69cb7cc730b3)
[Create Next App.webm](https://github.com/Hariz0n/shri-react-hw-2023/assets/55204364/a334182a-881c-4770-a594-a6e32f8e86fb)

Также так и не получил ответа по селекторам и ограничениям фильтра. Что с ними не так?

**Comment by Hariz0n** [comment]
Сейчас попросил сокомандника сбилдить проект. Проект успешно сбилдился.

Если тут не удобно писать, то можешь написать в тг https://t.me/Hariz0n
